### ISSUE TITLE
latest release can't deploy service to v0.9 cluster

### ISSUE THREAD

**Issue by mchmarny** [knative/client#423] opened 2019-10-01 03:31 UTC
## What version of Knative Client?

v0.2.0

## What version of Knative Serving running on your cluster?

0.9

## Expected Behavior

```shell
kn service create prime \
  --image gcr.io/cloudylabs-public/maxprime \
  --namespace demo
```

results in service deployed 

## Actual Behavior

Service 'prime' successfully created in namespace 'demo'.
Waiting for service 'prime' to become ready ...

With kn waiting for the service to become available forever 

## Steps to Reproduce the Problem

run the following command against v0.9 Knative Service cluster  

```shell
kn service create prime \
  --image gcr.io/cloudylabs-public/maxprime \
  --namespace demo
```

**Comment by rhuss** [comment] 2019-10-01 09:56
> With kn waiting for the service to become available forever

That's interesting as there is supposed to be a timeout after 60s (which actually works and is independent on any Knative serving version). When you say 'forever' how long is this :) ?

After you stopped the command, has a Knative service be created (e.g. `kubectl get ksvc`). If so, could you check the status section of the resource (`kubectl get ksvc prime -o yaml`) and post it here ?

If a Knative service has been created, can you use `kn service list` and `kn service describe prime`) ?

Also, could you please try to recreate the service with the option `--log-http` ?

**Comment by drnic** [comment] 2019-10-01 21:00
FWIW - latest nightly `kn` worked for me against knative-service 0.9.0/istio 1.3.0.

**Comment by drnic** [comment] 2019-10-02 05:14
I get the issue sometimes:

```
$ kn service create sample-app-nodejs --image starkandwayne/sample-app-nodejs:latest --force --log-http
===== REQUEST =====
GET /apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs HTTP/1.1
Host: 35.189.6.125
User-Agent: kn/v0.0.0 (darwin/amd64) kubernetes/$Format
Accept: application/json, */*
Authorization: *******************************************************************************************************************************************************
Accept-Encoding: gzip


===== RESPONSE =====
HTTP/2.0 200 OK
Content-Length: 1565
Audit-Id: 2ac204e2-c72f-4fd3-a562-29ba63aa5133
Content-Type: application/json
Date: Wed, 02 Oct 2019 05:10:02 GMT

{"apiVersion":"serving.knative.dev/v1alpha1","kind":"Service","metadata":{"annotations":{"serving.knative.dev/creator":"drnic@starkandwayne.com","serving.knative.dev/lastModifier":"drnic@starkandwayne.com"},"creationTimestamp":"2019-10-02T04:31:57Z","generation":4,"name":"sample-app-nodejs","namespace":"default","resourceVersion":"14081","selfLink":"/apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs","uid":"91ea7901-e4cd-11e9-b8e8-42010a980121"},"spec":{"template":{"metadata":{"annotations":{"client.knative.dev/user-image":"starkandwayne/sample-app-nodejs:latest"},"creationTimestamp":null,"name":"sample-app-nodejs-pxnvv-1"},"spec":{"containerConcurrency":0,"containers":[{"image":"starkandwayne/sample-app-nodejs:latest","name":"user-container","readinessProbe":{"successThreshold":1,"tcpSocket":{"port":0}},"resources":{}}],"timeoutSeconds":300}},"traffic":[{"latestRevision":true,"percent":100}]},"status":{"address":{"url":"http://sample-app-nodejs.default.svc.cluster.local"},"conditions":[{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"ConfigurationsReady"},{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"Ready"},{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"RoutesReady"}],"latestCreatedRevisionName":"sample-app-nodejs-pxnvv-1","latestReadyRevisionName":"sample-app-nodejs-pxnvv-1","observedGeneration":4,"traffic":[{"latestRevision":true,"percent":100,"revisionName":"sample-app-nodejs-pxnvv-1"}],"url":"http://sample-app-nodejs.default.example.com"}}

 * * * * * *
===== REQUEST =====
GET /apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs HTTP/1.1
Host: 35.189.6.125
User-Agent: kn/v0.0.0 (darwin/amd64) kubernetes/$Format
Accept: application/json, */*
Authorization: *******************************************************************************************************************************************************
Accept-Encoding: gzip


===== RESPONSE =====
HTTP/2.0 200 OK
Content-Length: 1565
Audit-Id: e4bd7d29-93f3-4b51-bb3d-152769bc220a
Content-Type: application/json
Date: Wed, 02 Oct 2019 05:10:02 GMT

{"apiVersion":"serving.knative.dev/v1alpha1","kind":"Service","metadata":{"annotations":{"serving.knative.dev/creator":"drnic@starkandwayne.com","serving.knative.dev/lastModifier":"drnic@starkandwayne.com"},"creationTimestamp":"2019-10-02T04:31:57Z","generation":4,"name":"sample-app-nodejs","namespace":"default","resourceVersion":"14081","selfLink":"/apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs","uid":"91ea7901-e4cd-11e9-b8e8-42010a980121"},"spec":{"template":{"metadata":{"annotations":{"client.knative.dev/user-image":"starkandwayne/sample-app-nodejs:latest"},"creationTimestamp":null,"name":"sample-app-nodejs-pxnvv-1"},"spec":{"containerConcurrency":0,"containers":[{"image":"starkandwayne/sample-app-nodejs:latest","name":"user-container","readinessProbe":{"successThreshold":1,"tcpSocket":{"port":0}},"resources":{}}],"timeoutSeconds":300}},"traffic":[{"latestRevision":true,"percent":100}]},"status":{"address":{"url":"http://sample-app-nodejs.default.svc.cluster.local"},"conditions":[{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"ConfigurationsReady"},{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"Ready"},{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"RoutesReady"}],"latestCreatedRevisionName":"sample-app-nodejs-pxnvv-1","latestReadyRevisionName":"sample-app-nodejs-pxnvv-1","observedGeneration":4,"traffic":[{"latestRevision":true,"percent":100,"revisionName":"sample-app-nodejs-pxnvv-1"}],"url":"http://sample-app-nodejs.default.example.com"}}

 * * * * * *
===== REQUEST =====
PUT /apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs HTTP/1.1
Host: 35.189.6.125
User-Agent: kn/v0.0.0 (darwin/amd64) kubernetes/$Format
Content-Length: 605
Accept: application/json, */*
Authorization: *******************************************************************************************************************************************************
Content-Type: application/json
Accept-Encoding: gzip

{"kind":"Service","apiVersion":"serving.knative.dev/v1alpha1","metadata":{"name":"sample-app-nodejs","namespace":"default","resourceVersion":"14081","creationTimestamp":null,"annotations":{"serving.knative.dev/creator":"drnic@starkandwayne.com","serving.knative.dev/lastModifier":"drnic@starkandwayne.com"}},"spec":{"template":{"metadata":{"name":"sample-app-nodejs-zhzgw-1","creationTimestamp":null,"annotations":{"client.knative.dev/user-image":"starkandwayne/sample-app-nodejs:latest"}},"spec":{"containers":[{"name":"","image":"starkandwayne/sample-app-nodejs:latest","resources":{}}]}}},"status":{}}

===== RESPONSE =====
HTTP/2.0 200 OK
Content-Length: 1565
Audit-Id: f5aabea6-60cd-4f9a-827c-c69470da344e
Content-Type: application/json
Date: Wed, 02 Oct 2019 05:10:02 GMT

{"apiVersion":"serving.knative.dev/v1alpha1","kind":"Service","metadata":{"annotations":{"serving.knative.dev/creator":"drnic@starkandwayne.com","serving.knative.dev/lastModifier":"drnic@starkandwayne.com"},"creationTimestamp":"2019-10-02T04:31:57Z","generation":5,"name":"sample-app-nodejs","namespace":"default","resourceVersion":"14473","selfLink":"/apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs","uid":"91ea7901-e4cd-11e9-b8e8-42010a980121"},"spec":{"template":{"metadata":{"annotations":{"client.knative.dev/user-image":"starkandwayne/sample-app-nodejs:latest"},"creationTimestamp":null,"name":"sample-app-nodejs-zhzgw-1"},"spec":{"containerConcurrency":0,"containers":[{"image":"starkandwayne/sample-app-nodejs:latest","name":"user-container","readinessProbe":{"successThreshold":1,"tcpSocket":{"port":0}},"resources":{}}],"timeoutSeconds":300}},"traffic":[{"latestRevision":true,"percent":100}]},"status":{"address":{"url":"http://sample-app-nodejs.default.svc.cluster.local"},"conditions":[{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"ConfigurationsReady"},{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"Ready"},{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"RoutesReady"}],"latestCreatedRevisionName":"sample-app-nodejs-pxnvv-1","latestReadyRevisionName":"sample-app-nodejs-pxnvv-1","observedGeneration":4,"traffic":[{"latestRevision":true,"percent":100,"revisionName":"sample-app-nodejs-pxnvv-1"}],"url":"http://sample-app-nodejs.default.example.com"}}

 * * * * * *
Service 'sample-app-nodejs' successfully replaced in namespace 'default'.
Waiting for service 'sample-app-nodejs' to become ready ... ===== REQUEST =====
GET /apis/serving.knative.dev/v1alpha1/namespaces/default/services?fieldSelector=metadata.name%3Dsample-app-nodejs&timeoutSeconds=90&watch=true HTTP/1.1
Host: 35.189.6.125
User-Agent: kn/v0.0.0 (darwin/amd64) kubernetes/$Format
Accept: application/json, */*
Authorization: *******************************************************************************************************************************************************
Accept-Encoding: gzip


===== RESPONSE =====
HTTP/2.0 200 OK
Connection: close
Audit-Id: 91fa7d4f-a493-497b-a598-94d6c2132661
Content-Type: application/json
Date: Wed, 02 Oct 2019 05:10:02 GMT

{"type":"ADDED","object":{"apiVersion":"serving.knative.dev/v1alpha1","kind":"Service","metadata":{"annotations":{"serving.knative.dev/creator":"drnic@starkandwayne.com","serving.knative.dev/lastModifier":"drnic@starkandwayne.com"},"creationTimestamp":"2019-10-02T04:31:57Z","generation":5,"name":"sample-app-nodejs","namespace":"default","resourceVersion":"14476","selfLink":"/apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs","uid":"91ea7901-e4cd-11e9-b8e8-42010a980121"},"spec":{"template":{"metadata":{"annotations":{"client.knative.dev/user-image":"starkandwayne/sample-app-nodejs:latest"},"creationTimestamp":null,"name":"sample-app-nodejs-zhzgw-1"},"spec":{"containerConcurrency":0,"containers":[{"image":"starkandwayne/sample-app-nodejs:latest","name":"user-container","readinessProbe":{"successThreshold":1,"tcpSocket":{"port":0}},"resources":{}}],"timeoutSeconds":300}},"traffic":[{"latestRevision":true,"percent":100}]},"status":{"address":{"url":"http://sample-app-nodejs.default.svc.cluster.local"},"conditions":[{"lastTransitionTime":"2019-10-02T05:10:02Z","message":"The Configuration is still working to reflect the latest desired specification.","reason":"OutOfDate","status":"Unknown","type":"ConfigurationsReady"},{"lastTransitionTime":"2019-10-02T05:10:02Z","message":"The Configuration is still working to reflect the latest desired specification.","reason":"OutOfDate","status":"Unknown","type":"Ready"},{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"RoutesReady"}],"latestCreatedRevisionName":"sample-app-nodejs-pxnvv-1","latestReadyRevisionName":"sample-app-nodejs-pxnvv-1","observedGeneration":4,"traffic":[{"latestRevision":true,"percent":100,"revisionName":"sample-app-nodejs-pxnvv-1"}],"url":"http://sample-app-nodejs.default.example.com"}}}
{"type":"MODIFIED","object":{"apiVersion":"serving.knative.dev/v1alpha1","kind":"Service","metadata":{"annotations":{"serving.knative.dev/creator":"drnic@starkandwayne.com","serving.knative.dev/lastModifier":"drnic@starkandwayne.com"},"creationTimestamp":"2019-10-02T04:31:57Z","generation":5,"name":"sample-app-nodejs","namespace":"default","resourceVersion":"14478","selfLink":"/apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs","uid":"91ea7901-e4cd-11e9-b8e8-42010a980121"},"spec":{"template":{"metadata":{"annotations":{"client.knative.dev/user-image":"starkandwayne/sample-app-nodejs:latest"},"creationTimestamp":null,"name":"sample-app-nodejs-zhzgw-1"},"spec":{"containerConcurrency":0,"containers":[{"image":"starkandwayne/sample-app-nodejs:latest","name":"user-container","readinessProbe":{"successThreshold":1,"tcpSocket":{"port":0}},"resources":{}}],"timeoutSeconds":300}},"traffic":[{"latestRevision":true,"percent":100}]},"status":{"address":{"url":"http://sample-app-nodejs.default.svc.cluster.local"},"conditions":[{"lastTransitionTime":"2019-10-02T05:10:02Z","status":"Unknown","type":"ConfigurationsReady"},{"lastTransitionTime":"2019-10-02T05:10:02Z","status":"Unknown","type":"Ready"},{"lastTransitionTime":"2019-10-02T05:08:37Z","status":"True","type":"RoutesReady"}],"latestCreatedRevisionName":"sample-app-nodejs-zhzgw-1","latestReadyRevisionName":"sample-app-nodejs-pxnvv-1","observedGeneration":5,"traffic":[{"latestRevision":true,"percent":100,"revisionName":"sample-app-nodejs-pxnvv-1"}],"url":"http://sample-app-nodejs.default.example.com"}}}
{"type":"MODIFIED","object":{"apiVersion":"serving.knative.dev/v1alpha1","kind":"Service","metadata":{"annotations":{"serving.knative.dev/creator":"drnic@starkandwayne.com","serving.knative.dev/lastModifier":"drnic@starkandwayne.com"},"creationTimestamp":"2019-10-02T04:31:57Z","generation":5,"name":"sample-app-nodejs","namespace":"default","resourceVersion":"14621","selfLink":"/apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs","uid":"91ea7901-e4cd-11e9-b8e8-42010a980121"},"spec":{"template":{"metadata":{"annotations":{"client.knative.dev/user-image":"starkandwayne/sample-app-nodejs:latest"},"creationTimestamp":null,"name":"sample-app-nodejs-zhzgw-1"},"spec":{"containerConcurrency":0,"containers":[{"image":"starkandwayne/sample-app-nodejs:latest","name":"user-container","readinessProbe":{"successThreshold":1,"tcpSocket":{"port":0}},"resources":{}}],"timeoutSeconds":300}},"traffic":[{"latestRevision":true,"percent":100}]},"status":{"address":{"url":"http://sample-app-nodejs.default.svc.cluster.local"},"conditions":[{"lastTransitionTime":"2019-10-02T05:10:19Z","status":"True","type":"ConfigurationsReady"},{"lastTransitionTime":"2019-10-02T05:10:19Z","message":"Traffic is not yet migrated to the latest revision.","reason":"TrafficNotMigrated","status":"Unknown","type":"Ready"},{"lastTransitionTime":"2019-10-02T05:10:19Z","message":"Traffic is not yet migrated to the latest revision.","reason":"TrafficNotMigrated","status":"Unknown","type":"RoutesReady"}],"latestCreatedRevisionName":"sample-app-nodejs-zhzgw-1","latestReadyRevisionName":"sample-app-nodejs-zhzgw-1","observedGeneration":5,"traffic":[{"latestRevision":true,"percent":100,"revisionName":"sample-app-nodejs-pxnvv-1"}],"url":"http://sample-app-nodejs.default.example.com"}}}
{"type":"MODIFIED","object":{"apiVersion":"serving.knative.dev/v1alpha1","kind":"Service","metadata":{"annotations":{"serving.knative.dev/creator":"drnic@starkandwayne.com","serving.knative.dev/lastModifier":"drnic@starkandwayne.com"},"creationTimestamp":"2019-10-02T04:31:57Z","generation":5,"name":"sample-app-nodejs","namespace":"default","resourceVersion":"14630","selfLink":"/apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs","uid":"91ea7901-e4cd-11e9-b8e8-42010a980121"},"spec":{"template":{"metadata":{"annotations":{"client.knative.dev/user-image":"starkandwayne/sample-app-nodejs:latest"},"creationTimestamp":null,"name":"sample-app-nodejs-zhzgw-1"},"spec":{"containerConcurrency":0,"containers":[{"image":"starkandwayne/sample-app-nodejs:latest","name":"user-container","readinessProbe":{"successThreshold":1,"tcpSocket":{"port":0}},"resources":{}}],"timeoutSeconds":300}},"traffic":[{"latestRevision":true,"percent":100}]},"status":{"address":{"url":"http://sample-app-nodejs.default.svc.cluster.local"},"conditions":[{"lastTransitionTime":"2019-10-02T05:10:19Z","status":"True","type":"ConfigurationsReady"},{"lastTransitionTime":"2019-10-02T05:10:19Z","message":"Ingress has not yet been reconciled.","reason":"IngressNotConfigured","status":"Unknown","type":"Ready"},{"lastTransitionTime":"2019-10-02T05:10:19Z","message":"Ingress has not yet been reconciled.","reason":"IngressNotConfigured","status":"Unknown","type":"RoutesReady"}],"latestCreatedRevisionName":"sample-app-nodejs-zhzgw-1","latestReadyRevisionName":"sample-app-nodejs-zhzgw-1","observedGeneration":5,"traffic":[{"latestRevision":true,"percent":100,"revisionName":"sample-app-nodejs-zhzgw-1"}],"url":"http://sample-app-nodejs.default.example.com"}}}
{"type":"MODIFIED","object":{"apiVersion":"serving.knative.dev/v1alpha1","kind":"Service","metadata":{"annotations":{"serving.knative.dev/creator":"drnic@starkandwayne.com","serving.knative.dev/lastModifier":"drnic@starkandwayne.com"},"creationTimestamp":"2019-10-02T04:31:57Z","generation":5,"name":"sample-app-nodejs","namespace":"default","resourceVersion":"14639","selfLink":"/apis/serving.knative.dev/v1alpha1/namespaces/default/services/sample-app-nodejs","uid":"91ea7901-e4cd-11e9-b8e8-42010a980121"},"spec":{"template":{"metadata":{"annotations":{"client.knative.dev/user-image":"starkandwayne/sample-app-nodejs:latest"},"creationTimestamp":null,"name":"sample-app-nodejs-zhzgw-1"},"spec":{"containerConcurrency":0,"containers":[{"image":"starkandwayne/sample-app-nodejs:latest","name":"user-container","readinessProbe":{"successThreshold":1,"tcpSocket":{"port":0}},"resources":{}}],"timeoutSeconds":300}},"traffic":[{"latestRevision":true,"percent":100}]},"status":{"address":{"url":"http://sample-app-nodejs.default.svc.cluster.local"},"conditions":[{"lastTransitionTime":"2019-10-02T05:10:19Z","status":"True","type":"ConfigurationsReady"},{"lastTransitionTime":"2019-10-02T05:10:20Z","status":"True","type":"Ready"},{"lastTransitionTime":"2019-10-02T05:10:20Z","status":"True","type":"RoutesReady"}],"latestCreatedRevisionName":"sample-app-nodejs-zhzgw-1","latestReadyRevisionName":"sample-app-nodejs-zhzgw-1","observedGeneration":5,"traffic":[{"latestRevision":true,"percent":100,"revisionName":"sample-app-nodejs-zhzgw-1"}],"url":"http://sample-app-nodejs.default.example.com"}}}

 * * * * * *

timeout: service 'sample-app-nodejs' not ready after 60 seconds
```

But I see the new revision created successfully; but the cli/api call doesn't return.

**Comment by mchmarny** [comment] 2019-10-02 20:36
yeo, Monday nightly worked for me too. `forever` was 5+ min

**Comment by rhuss** [comment] 2019-10-04 08:02
> timeout: service 'sample-app-nodejs' not ready after 60 seconds

This means, that it takes longer than 60s until the service becomes ready so that a timeout applies for this client operation. This does not imply that the service fails. A common reason for taking that long is that images need to be pulled from a remote registry to nodes. (Unfortunately, this is not deterministic, e.g. even when a service has been already deployed and then deployed again with the same image, the pods created can end up on different nodes which don't have the image yet locally).

We can do better here, though, to make the timeout much longer and only stop on a real error condition. However, when the timeout is increased we also do need a progress indicator in the UI (growing line of dots, a real progress meter, ...)

**Comment by rhuss** [comment] 2019-10-04 08:03
@mchmarny 

> yeo, Monday nightly worked for me too. `forever` was 5+ min

With 5mins do you refer to the time it took for the CLI command to return (that would mean that the internal timeout of 60s failed) or that the service did not become ready within 5 minutes (that could be the case e.g. on slow connection when a larger container image needs to be pulled) ?

**Comment by drnic** [comment] 2019-10-04 08:53
I think an API call isn’t returning even though the work has been completed.
-- 
Dr Nic Williams
Stark & Wayne LLC
http://starkandwayne.com
+61 437 276 076
twitter @drnic

**Comment by rhuss** [comment] 2019-10-04 13:36
@drnic your log output is interesting as the last even indicate that all three conditions are `True` which is the trigger for the client to exit with success. Instead, it seems that `kn` continues to wait and then eventually times out. 

I will have a look now and hopefully I can reproduce it.

**Comment by rhuss** [comment] 2019-10-04 14:37
> @drnic your log output is interesting as the last even indicate that all three conditions are `True` which is the trigger for the client to exit with success. Instead, it seems that `kn` continues to wait and then eventually times out.

I can confirm this issue, which however only occurs together with `--log-http`. I.e. it seems that no events arrive in the wait loop as they are consumed by the http logging.

Without logging, it works for me if the image is already fixed. If not (i.e. the initial create), I see the following:

```
$ kn service create sample-app-nodejs --image starkandwayne/sample-app-nodejs:latest
Service 'sample-app-nodejs' successfully created in namespace 'default'.
Waiting for service 'sample-app-nodejs' to become ready ...
timeout: service 'sample-app-nodejs' not ready after 60 seconds

$ kn service delete sample-app-nodejs
Service 'sample-app-nodejs' successfully deleted in namespace 'default'.

$ kn service create sample-app-nodejs --image starkandwayne/sample-app-nodejs:latest
Service 'sample-app-nodejs' successfully created in namespace 'default'.
Waiting for service 'sample-app-nodejs' to become ready ... OK

Service URL:
http://sample-app-nodejs.default.example.com
```

Note that the test is on a (single-node) minikube installation and since the image has a size of ~ 1.3 GB, this takes longer than 60s to download. The second service creation is much faster (the image is already pulled), and so succeeds within the timeout.

The takeaway for me here is:

* The timeout should be much longer and some progress indicator should be shown
* `--log-http` is broken as it 'eats up' watch events which then always ends up that kn runs into a timeout

@mchmarny this however does *not* explain why for you `kn service create` never returns. It should always return at most after 60s. Could you please a sample command to that I could hopefully reproduce this behaviour ?

**Comment by rhuss** [comment] 2019-10-04 17:05
@sixolet The reason actually why watching doesn't work is 

https://github.com/knative/client/blob/2f7fa6a7c20414463c387ac68e3043335032a971/pkg/util/logging_http_transport.go#L83

This will read the response until EOF (i.e closed by the server), however, for a watch this will never be the case (it's an endless stream which needs to be closed by the client). So kn reads the stream until it runs into the timeout of 60s in which case it returns.

I'm not sure that consuming the response in a round-tripper proxy is a good thing.

Maybe we should just delegate to the general debugging of go-client, which uses `github.com/golang/glog` for low level debugging (headers and actions, but no response content) ?

**Comment by rhuss** [comment] 2019-10-04 17:09
btw, this is how the DebugWrapper is turned on in client-go: https://github.com/kubernetes/client-go/blob/ec28f1ce4612672d4ba794030d27c62873af14f1/transport/round_trippers.go#L68-L81

**Comment by rhuss** [comment] 2019-10-04 17:10
My suggestion would be to take over this level-based debugging as part of the #333 story.

**Comment by rhuss** [comment] 2019-10-04 17:11
I'm on the other half of this issue, for allowing a higher (and configurable) timeout for watching, so that a timeout should occur must less frequently (even for initial deployments where an image needs to be fully fetched)

**Comment by rhuss** [comment] 2020-02-05 12:22
Let's track the other half of the issue over there at #485 so I'm closing this issue. Let's followup over there.

**Closed by rhuss** 2020-02-05 12:22 UTC
Labels: kind/bug
